labels:
- name: bug
  color: ffb3ba
  description: Something isn't working
- name: feature
  color: ffdfba
  description: New feature or request
- name: enhancement
  color: ffffba
  description: Enhancement to existing feature
- name: documentation
  color: baffc9
  description: Documentation related
- name: testing
  color: bae1ff
  description: Testing related
- name: priority
  color: ff6f61
  description: High priority issue
- name: discussion
  color: fbb347
  description: Discussion related
- name: question
  color: ffd700
  description: Question or inquiry
- name: help wanted
  color: 77dd77
  description: Help wanted
- name: invalid
  color: 779ecb
  description: This doesn't seem right
- name: wontfix
  color: ffffff
  description: This will not be worked on
